version: "3.9"

services:
  fastapi_beer_app:
    build: .
    image: "fastapi_beer_image"
    container_name: "fastapi_beer_app"
    volumes:
      - .:/app
      - /virtual-env
    ports:
      - 8000:8000
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - "./.env"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgressql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - "./.env"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
