version: '3.8'

services:
  app:
    image: beer-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./:/app:delegated
    ports:
    - "9080:8080"
#    depends_on:
#      - db
#
#  db:
#    image: postgres
#    env_file:
#      - .env
#    ports:
#      - '5432:5432'
